CORRECTION_CONSIDERATION_THRESHOLD = 0.99
OTHER_CLASS_MIN_THRESH_WITH_CORRECTION = 0.99
CORRECTION_CONFIDENCE_THRESHOLD = 0.01
FIRST_DETECTION_CONFIDENCE = 0.98
SECOND_DETECTION_CONFIDENCE = 0.95
CORRECTION_CONFIDENCE_THRESHOLD_WHEN_NO = 0.005